spring:
  profiles:
    active: web
  config:
    import: classpath:common.yml
  redis:
    host: 198.46.175.142
    port: 6379
    password: Wsldf981126!
    database: 0
  datasource:
    url: jdbc:mysql://198.46.175.142:3306/lee?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: lee
    password: Wsldf981126
    driver-class-name: com.mysql.cj.jdbc.Driver

    # MyBatis Plus 配置（可选）
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

bsc:
  rpc-url: https://bsc-mainnet.nodereal.io/v1/674af95f1d044f1386283941fce563c8
  ws-url: wss://bsc-mainnet.nodereal.io/ws/v1/674af95f1d044f1386283941fce563c8
  start-block: 72862765
  matcher-address: 0x5F45344126D6488025B0b84A3A8189F2487a7246
  token-contract: 0x55d398326f99059fF775485246999027B3197955
  token-decimals: 18
  batch-size: 2000
