CREATE TABLE IF NOT EXISTS bsc_matcher_sync_status (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    last_block BIGINT NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    KEY idx_last_block (last_block)
);
