server:
  port: 8082
  servlet:
    context-path: /alpha
spring:
  config:
    import: classpath:common.yml
  redis:
    host: 198.46.175.142
    port: 6379
    password: Wsldf981126!
    database: 0
  datasource:
    url: jdbc:mysql://198.46.175.142:3306/lee?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: lee
    password: Wsldf981126
    driver-class-name: com.mysql.cj.jdbc.Driver

  # 确保启用 web 环境
  main:
    web-application-type: servlet

# MyBatis Plus 配置（可选）
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

bsc:
  rpc-url: https://1rpc.io/bnb

# 确保服务器配置正确
